# Generated by Django 5.2.6 on 2025-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothes', 'Clothes'), ('equipment', 'Equipment'), ('accessories', 'Accessories')], default='shoes', max_length=20),
        ),
    ]
