# Generated by Django 5.2.6 on 2025-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothes', 'Clothes'), ('equipment', 'Equipment'), ('accessories', 'Accessories'), ('misc', 'Miscellaneous')], default='shoes', max_length=20),
        ),
    ]
