# Generated by Django 5.2.6 on 2025-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_alt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
